import { draftDb } from '@/lib/draftsDb';

const AGENT_URL = process.env.AGENT_URL || 'https://article-agent-zk00.onrender.com';

/**
 * Why build CALLBACK_URL from env instead of hardcoding:
 * A hardcoded secret (like '?secret=sherly') is committed to the repository and visible
 * to anyone with git access. Using WEBHOOK_SECRET / ADMIN_SECRET from env vars ensures
 * the secret is never stored in source control and can be rotated without a code deploy.
 *
 * Why WEBHOOK_SECRET falls back to ADMIN_SECRET:
 * Both guard the same webhook endpoint. Keeping a single secret for both avoids
 * secret sprawl while still allowing a dedicated WEBHOOK_SECRET when needed.
 *
 * Why we throw instead of silently falling back:
 * A misconfigured callback URL causes the Python agent to fire results into a broken
 * endpoint, leaving articles stuck in 'generating' forever with no error. Failing loudly
 * at call-time surfaces the misconfiguration immediately.
 */
function buildCallbackUrl(): string {
  // 1. Prefer an explicitly configured full callback URL (easiest override in production).
  if (process.env.DASHBOARD_CALLBACK_URL) {
    const overrideUrl = process.env.DASHBOARD_CALLBACK_URL;
    // Why validate the override URL: If someone set DASHBOARD_CALLBACK_URL to a legacy value
    // that still contains '?secret=...', it would silently bypass all the security hardening
    // we applied to stop secrets leaking into network logs and proxy access logs.
    // Logging a clear warning here surfaces this misconfiguration immediately.
    if (overrideUrl.includes('?secret=') || overrideUrl.includes('&secret=')) {
      console.warn(
        '[agentHelper] SECURITY WARNING: DASHBOARD_CALLBACK_URL contains a "?secret=" query parameter. ' +
        'This leaks your webhook secret into server access logs. ' +
        'Remove the secret from the URL — the webhook now authenticates via the Authorization: Bearer header.'
      );
    }
    return overrideUrl;
  }

  // 2. Build from base site URL + whichever secret is configured.
  const webhookSecret = process.env.WEBHOOK_SECRET || process.env.ADMIN_SECRET;
  if (!webhookSecret) {
    // Fail-closed: do not call the agent without a valid callback URL.
    throw new Error(
      '[agentHelper] Configuration Error: WEBHOOK_SECRET (or ADMIN_SECRET) must be set. ' +
      'The agent callback URL cannot be built without a secret.'
    );
  }

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://arabiakhaleej.com';
  return `${baseUrl}/api/webhook`;
}

/**
 * Shared helper to trigger the external article generation agent.
 * This ensures the topic is added to the Redis draft queue before calling the agent,
 * and updates the status to 'error' if the external agent fails immediately.
 * 
 * @param topic The trending or manually inputted topic to generate an article for.
 */
export async function triggerAgentGeneration(topic: string) {
  // Build the callback URL dynamically (throws if secrets are not configured)
  const callbackUrl = buildCallbackUrl();

  // Create initial tracking draft with a 7-day TTL so orphaned 'generating' entries
  // do not accumulate forever if the agent never responds or errors silently.
  // Why 7 days: enough runway for any delayed agent run while preventing perpetual Redis pollution.
  await draftDb.setDraft(topic, {
    topic,
    status: 'generating',
    timestamp: Date.now()
  }, { ttlSeconds: 60 * 60 * 24 * 7 }); // 7 days

  // Forward the request to the Python generation agent
  const res = await fetch(`${AGENT_URL}/v1/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      topic,
      callback_url: callbackUrl
    })
  });

  if (!res.ok) {
    // Why self-healing state: If the Python agent rejects our request, we immediately update
    // the status of the topic in Redis to 'error' to avoid leaving the dashboard in a perpetual 'generating' state.
    console.error(`[generate] External article agent rejected generation for: "${topic}". Status: ${res.status}`);
    // Keep errored drafts for 2 days so admins can investigate, then auto-clean.
    // Why 2 days instead of 7: error drafts have no useful content to review or publish;
    // shorter TTL avoids dashboard clutter from stale failures.
    await draftDb.setDraft(topic, { 
      topic, 
      status: 'error', 
      error: `Agent rejected with status: ${res.status}`, 
      timestamp: Date.now() 
    }, { ttlSeconds: 60 * 60 * 24 * 2 }); // 2 days
    throw new Error(`Agent rejected request with status: ${res.status}`);
  }
}

/**
 * Sanitizes and repairs markdown content generated by LLM agents.
 * 
 * Fixes:
 * 1. Extracts stray JSON blocks at the tail end of the document.
 * 2. Repairs tab-separated or smushed tables into proper GFM syntax.
 * 3. Ensures GitHub-style alerts (e.g. [!TIP]) are properly blockquoted (> [!TIP]).
 */
export function sanitizeAgentMarkdown(content: string): string {
  if (!content) return content;

  let text = content;

  // 1. Strip trailing JSON blocks if the LLM leaked its formatting wrapper
  const jsonIndex = text.lastIndexOf('{"content":');
  if (jsonIndex > -1 && jsonIndex > text.length - 2000) {
    if (jsonIndex > 50) {
      text = text.substring(0, jsonIndex).trim();
    } else {
      try {
        const parsed = JSON.parse(text.substring(jsonIndex));
        if (parsed.content) text = parsed.content;
      } catch (e) {
        text = text.substring(0, jsonIndex).trim();
      }
    }
  }

  // 2. Repair tab-separated pseudo-tables and un-quoted alerts
  const lines = text.split('\n');
  const repairedLines: string[] = [];
  let inTable = false;
  let inAlert = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Check for tab-separated rows without pipes
    if (line.includes('\t') && !line.includes('|')) {
      const cells = line.split('\t').map(c => c.trim()).filter(Boolean);
      if (cells.length > 1) {
        const markdownRow = `| ${cells.join(' | ')} |`;
        
        if (!inTable) {
          repairedLines.push(markdownRow);
          const sepRow = `|${cells.map(() => '---').join('|')}|`;
          repairedLines.push(sepRow);
          inTable = true;
          continue;
        } else {
          repairedLines.push(markdownRow);
          continue;
        }
      }
    } else if (trimmed.startsWith('|')) {
      inTable = true;
    } else if (trimmed === '') {
      inTable = false;
    }

    // Check for un-quoted GitHub alerts
    const alertMatch = trimmed.match(/^\[!(TIP|NOTE|IMPORTANT|WARNING|CAUTION)\]/i);
    if (alertMatch && !trimmed.startsWith('>')) {
      repairedLines.push(`> ${trimmed}`);
      inAlert = true;
      continue;
    }

    if (inAlert) {
      if (trimmed === '') {
        inAlert = false;
        repairedLines.push('');
      } else {
        repairedLines.push(`> ${trimmed}`);
      }
      continue;
    }

    repairedLines.push(line);
  }

  return repairedLines.join('\n');
}
