/**
 * @file lib/ai.ts
 * @module AI
 * @description Arabia Khaleej — AI Intelligence Layer (Groq)
 *
 * Handles all interactions with the Groq inference API for one purpose:
 *   1. Full article generation via `generateGCCInsight()`
 *
 * ## Authorship Policy
 * Article authors are NEVER generated by the AI model. They are assigned from the
 * verified editorial team defined in `EDITORIAL_AUTHORS` and displayed on the `/about` page.
 * This ensures consistent E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness)
 * authorship signals across all content, satisfying Google AdSense and Search quality requirements.
 *
 * ## AI Transparency
 * Content is AI-assisted, with all articles undergoing human editorial review before publication.
 * See our Disclaimer page for full details.
 *
 * @requires process.env.GROQ_API_KEY
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

import { GROQ_API_URL } from '@/lib/constants/api';

/**
 * Raw response shape returned by the Groq OpenAI-compatible Chat Completions API.
 * Only the fields consumed by this module are declared.
 */
export interface GroqResponse {
  choices: {
    message: {
      /** JSON-encoded article or topic list string */
      content: string;
    };
  }[];
}

/**
 * Structured output of a generated GCC editorial article.
 *
 * @property title    - SEO-optimised article headline
 * @property content  - Full article body in Markdown format (≥1500 words)
 * @property category - Editorial category; one of the six canonical values
 * @property author   - Verified editorial persona (assigned deterministically, never AI-generated)
 * @property summary  - 160-character meta description for SEO
 */
export interface GCCInsightResponse {
  title: string;
  content: string;
  category: string;
  author: {
    /** Author display name in English */
    name: string;
    /** Author display name in Arabic */
    nameAr: string;
    /** Author professional title in English */
    title: string;
    /** Author professional title in Arabic */
    titleAr: string;
  };
  summary: string;
}

// ---------------------------------------------------------------------------
// Editorial Author Registry
// ---------------------------------------------------------------------------

/**
 * Canonical editorial team registry.
 *
 * **IMPORTANT:** This object must stay synchronised with:
 *   - `lib/i18n/editorial.ts`  → analyst{1|2|3}{Name|Role|Bio} keys
 *   - `app/(legal)/about/AboutClient.tsx` → rendered author cards
 *
 * Any addition or rename here must be reflected in both files above
 * to maintain consistent E-E-A-T signals across the platform.
 */
const EDITORIAL_AUTHORS: Record<string, GCCInsightResponse['author']> = {
  default: {
    name: "Arabia Khaleej Editorial Team",
    nameAr: "هيئة تحرير عربية خليج",
    title: "Editorial Board",
    titleAr: "هيئة التحرير",
  },
};

/**
 * Fallback author used for all content.
 * Represents the collective editorial board rather than a named individual.
 */
const DEFAULT_AUTHOR: GCCInsightResponse['author'] = {
  name: "Arabia Khaleej Editorial Team",
  nameAr: "هيئة تحرير عربية خليج",
  title: "Editorial Board",
  titleAr: "هيئة التحرير",
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a structured, long-form GCC editorial article via the Groq API.
 *
 * The AI model produces the title, Markdown body, category, and summary.
 * The author is **not** sourced from the AI — it is looked up from `EDITORIAL_AUTHORS`
 * using the returned category as the key. This prevents hallucinated author names and
 * ensures all articles are attributed to verifiable, named personas.
 *
 * @param country - GCC country the article focuses on (e.g. "Saudi Arabia")
 * @param topic   - Specific subject or angle for the article
 * @param lang    - Output language: `'en'` for English, `'ar'` for Arabic
 * @param model   - Groq model identifier. Defaults to the high-quality 70B variant.
 *                  Use `"llama-3.1-8b-instant"` for faster, lower-cost drafting.
 *
 * @returns Fully structured `GCCInsightResponse` with deterministic author assignment
 * @throws  Error if `GROQ_API_KEY` is missing or the API returns a non-OK status
 */
export async function generateGCCInsight(
   country: string,
   topic: string,
   lang: 'en' | 'ar',
   model: "llama-3.3-70b-versatile" | "llama-3.1-8b-instant" = "llama-3.3-70b-versatile"
): Promise<GCCInsightResponse> {
   const apiKey = process.env.GROQ_API_KEY;
   if (!apiKey) {
     throw new Error("GROQ_API_KEY is not configured.");
   }

    const prompt = lang === 'en'
      ? `Write a comprehensive, authoritative editorial article about ${country} focusing on ${topic}.
The article must be at least 1100 words with clear sections and institutional-grade analysis.

REQUIRED ELEMENTS FOR QUALITY:
- Specific company names from ${country}/GCC (e.g., "Saudi Aramco", "Emirates NBD")
- Cite at least 2 specific official sources with dates
- Include concrete statistics or policy numbers
- Reference specific government initiatives or investment values
- Add specific regional examples that demonstrate local context

Focus: Accurate regional context, cultural depth, economic significance, and forward-looking strategic analysis.
Tone: Professional, sophisticated, and informative.
Format: Return a JSON object with the following fields:
- title: A professional SEO title.
- content: The full article in Markdown format.
- category: One of [Fiscal, Geopolitics, Culture, Technology, Infrastructure, Energy].
- summary: A 160-character professional summary.

STRICT RULES:
1. DO NOT include any introductory preamble.
2. DO NOT include an author field — it will be assigned editorially.
3. Use professional British English.
4. Return VALID JSON only.`
      : `اكتب مقالاً تحريرياً شاملاً ومعمّقاً عن ${country} مع التركيز على ${topic}.
يجب أن لا يقل عن 1100 كلمة مع أقسام واضحة وتحليل بمستوى مؤسسي.

العناصر المطلوبة للجودة:
- أسماء شركات محددة من ${country}/الخليج
- اقتباس مصادر رسمية محددة بتواريخ
- إدراج إحصاءات ملموسة أو أرقام سياسية
- الإشارة إلى مبادرات حكومية محددة أو قيم استثمارية
- أمثلة إقليمية محددة توضح السياق المحلي

التركيز: السياق الإقليمي الدقيق، العمق الثقافي، الأهمية الاقتصادية، والتحليل الاستراتيجي الاستشرافي.
الأسلوب: صوت تحريري مهني وراقي.
التنسيق: أرجع كائن JSON يحتوي على الحقول التالية:
- title: عنوان احترافي مهيأ لمحركات البحث.
- content: المقال كاملاً بتنسيق Markdown.
- category: واحد من [Fiscal, Geopolitics, Culture, Technology, Infrastructure, Energy].
- summary: ملخص احترافي من 160 حرفاً.

قواعد صارمة:
1. لا تدرج أي نص تمهيدي.
2. لا تُضمّن حقل المؤلف — سيتم تعيينه تحريرياً.
3. استخدم لغة عربية فصحى رصينة واحترافية.
4. أرجع JSON صالحاً فقط.`;

   try {
     const response = await fetch(GROQ_API_URL, {
       method: "POST",
       headers: {
         "Authorization": `Bearer ${apiKey}`,
         "Content-Type": "application/json",
       },
       body: JSON.stringify({
         model,
         messages: [
           {
             role: "system",
             content:
               "You are a senior regional analyst and editor for Arabia Khaleej. " +
               "You provide structured, professional intelligence in JSON format. " +
               "Never invent author names. " +
               "NEVER produce content that violates AdSense policies: no scraped/copyrighted text, " +
               "no thin content, no unqualified medical/financial claims, no deceptive information, " +
               "and no gambling or illegal-substance promotion per article.",
           },
           { role: "user", content: prompt },
         ],
         temperature: 0.6,
         max_tokens: 8192,
         response_format: { type: "json_object" },
       }),
     });

     if (!response.ok) {
       let errorData = {};
       try {
         errorData = await response.json();
       } catch (parseErr) {
         console.error('Failed to parse Groq error response as JSON:', parseErr);
       }
       throw new Error(`Groq API Error: ${response.status} ${JSON.stringify(errorData)}`);
     }

     const data: GroqResponse = await response.json();
     const parsed = JSON.parse(data.choices[0].message.content);

     const category: string = parsed.category || "Strategy";

     // Look up the verified editorial author (default for all content)
     const author = EDITORIAL_AUTHORS['default'] ?? DEFAULT_AUTHOR;

     return {
       title: parsed.title || `${country}: ${topic}`,
       content: parsed.content || "",
       category,
       author,
       summary: parsed.summary || "",
     };
   } catch (error) {
     console.error("GCC Insight Generation Failed:", error);
     throw error;
   }
}