/**
 * @file lib/ai.ts
 * @module AI
 * @description Arabia Khaleej — AI Intelligence Layer (Groq)
 *
 * Handles all interactions with the Groq inference API for two purposes:
 *   1. Full article generation via `generateGCCInsight()`
 *   2. Topic discovery via `generateTrendingTopics()`
 *
 * ## Authorship Policy
 * Article authors are NEVER generated by the AI model. They are deterministically
 * assigned from the three verified editorial personas defined in `EDITORIAL_AUTHORS`
 * and displayed on the `/about` page. This ensures consistent E-E-A-T (Experience,
 * Expertise, Authoritativeness, Trustworthiness) authorship signals across all content,
 * satisfying Google AdSense and Search quality requirements.
 *
 * ## Author → Category Mapping
 * | Category                        | Author              |
 * |---------------------------------|---------------------|
 * | Fiscal, Geopolitics, Energy     | Dr. Faisal Al-Saud  |
 * | Culture                         | Amna Al-Hashimi     |
 * | Technology, Infrastructure      | Marcus Thorne       |
 * | Any unrecognised category       | Editorial Board     |
 *
 * @requires process.env.GROQ_API_KEY
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Raw response shape returned by the Groq OpenAI-compatible Chat Completions API.
 * Only the fields consumed by this module are declared.
 */
export interface GroqResponse {
  choices: {
    message: {
      /** JSON-encoded article or topic list string */
      content: string;
    };
  }[];
}

/**
 * Structured output of a generated GCC editorial article.
 *
 * @property title    - SEO-optimised article headline
 * @property content  - Full article body in Markdown format (≥1500 words)
 * @property category - Editorial category; one of the six canonical values
 * @property author   - Verified editorial persona (assigned deterministically, never AI-generated)
 * @property summary  - 160-character meta description for SEO
 */
export interface GCCInsightResponse {
  title: string;
  content: string;
  category: string;
  author: {
    /** Author display name in English */
    name: string;
    /** Author display name in Arabic */
    nameAr: string;
    /** Author professional title in English */
    title: string;
    /** Author professional title in Arabic */
    titleAr: string;
  };
  summary: string;
}

// ---------------------------------------------------------------------------
// Editorial Author Registry
// ---------------------------------------------------------------------------

/**
 * Canonical editorial team registry.
 *
 * **IMPORTANT:** This object must stay synchronised with:
 *   - `lib/i18n/editorial.ts`  → analyst{1|2|3}{Name|Role|Bio} keys
 *   - `app/(legal)/about/AboutClient.tsx` → rendered author cards
 *
 * Any addition or rename here must be reflected in both files above
 * to maintain consistent E-E-A-T signals across the platform.
 */
const EDITORIAL_AUTHORS: Record<string, GCCInsightResponse['author']> = {
  Fiscal: {
    name: "Dr. Faisal Al-Saud",
    nameAr: "د. فيصل آل سعود",
    title: "Chief Regional Strategist",
    titleAr: "رئيس الاستراتيجيات الإقليمية",
  },
  Geopolitics: {
    name: "Dr. Faisal Al-Saud",
    nameAr: "د. فيصل آل سعود",
    title: "Chief Regional Strategist",
    titleAr: "رئيس الاستراتيجيات الإقليمية",
  },
  Energy: {
    name: "Dr. Faisal Al-Saud",
    nameAr: "د. فيصل آل سعود",
    title: "Chief Regional Strategist",
    titleAr: "رئيس الاستراتيجيات الإقليمية",
  },
  Culture: {
    name: "Amna Al-Hashimi",
    nameAr: "آمنة الهاشمي",
    title: "Director of Cultural Intelligence",
    titleAr: "مديرة الاستخبارات الثقافية",
  },
  Technology: {
    name: "Marcus Thorne",
    nameAr: "ماركوس ثورن",
    title: "Head of Market Dynamics",
    titleAr: "رئيس ديناميكيات السوق",
  },
  Infrastructure: {
    name: "Marcus Thorne",
    nameAr: "ماركوس ثورن",
    title: "Head of Market Dynamics",
    titleAr: "رئيس ديناميكيات السوق",
  },
};

/**
 * Fallback author used when the AI returns an unrecognised category.
 * Represents the collective editorial board rather than a named individual.
 */
const DEFAULT_AUTHOR: GCCInsightResponse['author'] = {
  name: "Arabia Khaleej Editorial",
  nameAr: "هيئة تحرير عربية خليج",
  title: "Editorial Board",
  titleAr: "هيئة التحرير",
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a structured, long-form GCC editorial article via the Groq API.
 *
 * The AI model produces the title, Markdown body, category, and summary.
 * The author is **not** sourced from the AI — it is looked up from `EDITORIAL_AUTHORS`
 * using the returned category as the key. This prevents hallucinated author names and
 * ensures all articles are attributed to verifiable, named personas.
 *
 * @param country - GCC country the article focuses on (e.g. "Saudi Arabia")
 * @param topic   - Specific subject or angle for the article
 * @param lang    - Output language: `'en'` for English, `'ar'` for Arabic
 * @param model   - Groq model identifier. Defaults to the high-quality 70B variant.
 *                  Use `"llama-3.1-8b-instant"` for faster, lower-cost drafting.
 *
 * @returns Fully structured `GCCInsightResponse` with deterministic author assignment
 * @throws  Error if `GROQ_API_KEY` is missing or the API returns a non-OK status
 */
export async function generateGCCInsight(
  country: string,
  topic: string,
  lang: 'en' | 'ar',
  model: "llama-3.3-70b-versatile" | "llama-3.1-8b-instant" = "llama-3.3-70b-versatile"
): Promise<GCCInsightResponse> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error("GROQ_API_KEY is not configured.");
  }

  const prompt = lang === 'en'
    ? `Write a comprehensive, authoritative editorial article about ${country} focusing on ${topic}.
       The article should be at least 1500 words with clear sections and institutional-grade analysis.
       Focus: Accurate regional context, cultural depth, economic significance, and forward-looking strategic analysis.
       Tone: Professional, sophisticated, and informative.
       Format: Return a JSON object with the following fields:
       - title: A professional SEO title.
       - content: The full article in Markdown format.
       - category: One of [Fiscal, Geopolitics, Culture, Technology, Infrastructure, Energy].
       - summary: A 160-character professional summary.

       STRICT RULES:
       1. DO NOT include any introductory preamble.
       2. DO NOT include an author field — it will be assigned editorially.
       3. Use professional British English.
       4. Return VALID JSON only.`
    : `اكتب مقالاً تحريرياً شاملاً ومعمّقاً عن ${country} مع التركيز على ${topic}.
       يجب أن لا يقل عن 1500 كلمة مع أقسام واضحة وتحليل بمستوى مؤسسي.
       التركيز: السياق الإقليمي الدقيق، العمق الثقافي، الأهمية الاقتصادية، والتحليل الاستراتيجي الاستشرافي.
       الأسلوب: صوت تحريري مهني وراقي.
       التنسيق: أرجع كائن JSON يحتوي على الحقول التالية:
       - title: عنوان احترافي مهيأ لمحركات البحث.
       - content: المقال كاملاً بتنسيق Markdown.
       - category: واحد من [Fiscal, Geopolitics, Culture, Technology, Infrastructure, Energy].
       - summary: ملخص احترافي من 160 حرفاً.

       قواعد صارمة:
       1. لا تدرج أي نص تمهيدي.
       2. لا تُضمّن حقل المؤلف — سيتم تعيينه تحريرياً.
       3. استخدم لغة عربية فصحى رصينة واحترافية.
       4. أرجع JSON صالحاً فقط.`;

  try {
    const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: "system",
            content: "You are a senior regional analyst and editor for Arabia Khaleej. You provide structured, professional intelligence in JSON format. Never invent author names.",
          },
          { role: "user", content: prompt },
        ],
        temperature: 0.6,
        max_tokens: 8192,
        response_format: { type: "json_object" },
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(`Groq API Error: ${response.status} ${JSON.stringify(errorData)}`);
    }

    const data: GroqResponse = await response.json();
    const parsed = JSON.parse(data.choices[0].message.content);

    const category: string = parsed.category || "Strategy";

    // Look up the verified editorial author by category.
    // Falls back to DEFAULT_AUTHOR for any unrecognised category value.
    const author = EDITORIAL_AUTHORS[category] ?? DEFAULT_AUTHOR;

    return {
      title: parsed.title || `${country}: ${topic}`,
      content: parsed.content || "",
      category,
      author,
      summary: parsed.summary || "",
    };
  } catch (error) {
    console.error("GCC Insight Generation Failed:", error);
    throw error;
  }
}

/**
 * Discovers a batch of strategic GCC editorial topics suitable for article generation.
 *
 * Uses the lightweight `llama-3.1-8b-instant` model for speed and cost efficiency,
 * since this is a planning/discovery step rather than content production.
 * Implements automatic retry with a 1.5-second backoff between attempts.
 *
 * @param lang    - Language context for topic relevance (does not affect the prompt language)
 * @param type    - `'gcc'` for GCC-focused topics; `'international'` for globally relevant
 *                  topics of interest to an Arab/Gulf audience
 * @param retries - Maximum number of retry attempts on failure (default: 2)
 *
 * @returns Array of `{ country, topic }` pairs, or an empty array on complete failure.
 *          Never throws — failures are logged and an empty array is returned.
 */
export async function generateTrendingTopics(
  lang: 'en' | 'ar',
  type: 'gcc' | 'international' = 'gcc',
  retries = 2
): Promise<{ country: string, topic: string }[]> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) return [];

  const context = type === 'gcc'
    ? "GCC region (Saudi Arabia, UAE, Qatar, Kuwait, Oman, Bahrain) focusing on strategic development, Vision 2030, and regional transformation."
    : "International trends relevant to the Arab world, such as global AI developments, tourism, and luxury sectors popular in the Gulf.";

  const prompt = `Generate 10 strategic regional intelligence topics for editorial analysis. 
  Current Reference Time: ${new Date().toISOString()}
  Context: ${context}
  
  CRITERIA:
  1. Focus on strategic development, regional intelligence, or social transformation.
  2. Avoid generic news; prioritize "Strategic Insights" and long-term impacts.
  3. Ensure geographic diversity across the GCC.
  4. Include topics on "Cultural Intelligence" (heritage, modern shifts, youth trends).

  Return ONLY a JSON array of objects with keys "country" and "topic". 
  Format: [{"country": "Saudi Arabia", "topic": "Cognitive Urbanism and the Future of NEOM"}, ...]`;

  for (let i = 0; i <= retries; i++) {
    try {
      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.1-8b-instant",
          messages: [{ role: "user", content: prompt }],
          temperature: 0.6,
          response_format: { type: "json_object" },
        }),
      });

      if (!response.ok) throw new Error(`Groq API Error: ${response.status}`);
      const data = await response.json();
      const rawContent = data.choices[0].message.content;

      const parsed = JSON.parse(rawContent);

      // The model sometimes wraps the array in a root object — handle all shapes.
      let topics: any[] = [];
      if (Array.isArray(parsed)) {
        topics = parsed;
      } else if (parsed.topics && Array.isArray(parsed.topics)) {
        topics = parsed.topics;
      } else {
        // Last resort: find the first array value in the response object
        const firstArray = Object.values(parsed).find(v => Array.isArray(v));
        if (firstArray) topics = firstArray as any[];
      }

      if (topics.length > 0) {
        return topics.map((t: any) => ({
          country: t.country || "GCC",
          topic: t.topic || "Regional Insight",
        }));
      }

      throw new Error("Invalid topics format from AI");
    } catch (error) {
      console.error(`Trending Topics Discovery Attempt ${i + 1} failed:`, error);
      // Wait 1.5s before retrying to avoid hammering the API on transient failures
      if (i < retries) await new Promise(r => setTimeout(r, 1500));
    }
  }

  return [];
}
