/**
 * @file lib/insights.ts
 * @module Insights
 * @description Arabia Khaleej — Insights Data Access Layer
 *
 * Provides all read access to editorial insight articles stored in Upstash Redis.
 * All articles are generated by the Cloudflare Worker pipeline and stored under
 * two Redis key patterns:
 *
 *   - `insights:list:{lang}`         — Compressed metadata array for listing pages
 *   - `insights:article:{slug}`      — Compressed full article object for detail pages
 *
 * This module never writes to Redis; all writes are owned by the Worker.
 *
 * ## Lookup Strategy (`getArticleBySlug`)
 * 1. Direct key hit on `insights:article:{slug}`
 * 2. Fuzzy match against the full list (handles legacy slug formats)
 * 3. Cross-language fallback (returns the other language if the requested one is missing)
 *
 * @see lib/redis.ts for compression/decompression helpers and cache duration constants
 */

import { redis, getWithCompression } from './redis';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Represents a single editorial insight article as stored in Redis.
 * Used for both list metadata and full article content.
 *
 * @property id          - Unique article identifier (typically a hash or UUID)
 * @property slug        - URL-safe slug used as the Redis key suffix and route segment
 * @property title       - Article headline
 * @property description - Short meta description (≤160 characters)
 * @property link        - Canonical URL path (e.g. `/insights/{slug}`)
 * @property pubDate     - ISO 8601 publication date string
 * @property source      - Originating source label (e.g. "Arabia Khaleej Editorial")
 * @property category    - Top-level content bucket: `'gcc'` or `'expat'`
 * @property language    - Primary language of the article
 * @property image       - Optional hero image URL
 * @property tags        - Optional array of topic tags for category filtering
 * @property content     - Optional full Markdown body (present on article keys, absent on list keys)
 */
export interface InsightItem {
  id: string;
  slug: string;
  title: string;
  description: string;
  link: string;
  pubDate: string;
  source: string;
  category: 'gcc' | 'expat';
  language: 'en' | 'ar' | 'regional';
  image?: string;
  tags?: string[];
  content?: string;
  author?: {
    id: string;
    name: string;
    role: string;
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Fetches article metadata from the language-specific Redis list key.
 *
 * Returns only list-level metadata (no full `content` field) for performance.
 * Results are deduplicated by slug and sorted newest-first before slicing.
 *
 * @param options.lang     - Language of the list to fetch (`'en'` or `'ar'`)
 * @param options.category - Optional category filter; matches against `tags`, `title`,
 *                           and `description` (case-insensitive substring match)
 * @param options.limit    - Maximum number of items to return (default: 100)
 *
 * @returns Sorted, deduplicated array of `InsightItem` objects (without full content)
 */
export async function getUnifiedInsights(options: {
  lang: 'en' | 'ar';
  category?: string | null;
  limit?: number;
}): Promise<InsightItem[]> {
  const { lang, category, limit = 100 } = options;

  let allItems: InsightItem[] = [];
  try {
    // Standardized Redis key format: insights:list:{lang}
    const stored = await getWithCompression<InsightItem[]>(`insights:list:${lang}`);
    if (stored && Array.isArray(stored)) {
      allItems = stored;
    }
  } catch (e) {
    console.error("Failed to fetch insights list from Redis:", e);
  }

  // Deduplicate by slug to handle any double-write edge cases from the Worker
  const allMap = new Map<string, InsightItem>();
  allItems.forEach(item => allMap.set(item.slug, item));
  allItems = Array.from(allMap.values());

  // Sort newest-first so listing pages always show the most recent content
  allItems.sort((a, b) => new Date(b.pubDate).getTime() - new Date(a.pubDate).getTime());

  // Apply optional category filter across tags, title, and description
  if (category) {
    const catLower = category.toLowerCase();
    allItems = allItems.filter(n => {
      return n.tags?.some(t => t.toLowerCase() === catLower) ||
             n.title.toLowerCase().includes(catLower) ||
             (n.description || "").toLowerCase().includes(catLower);
    });
  }

  return allItems.slice(0, limit);
}

/**
 * Fetches a single full article by its URL slug.
 *
 * Implements a three-stage lookup strategy to maximise hit rate across
 * different slug formats and language variants:
 *
 * 1. **Direct key lookup** — `insights:article:{slug}` (fastest path)
 * 2. **Fuzzy list match** — scans the metadata list for slugs sharing the same
 *    base prefix (handles hash-suffixed slugs from the migration script)
 * 3. **Cross-language fallback** — attempts the same slug against the other
 *    language's article key when the requested language returns nothing
 *
 * @param slug - URL slug of the article (case-insensitive; normalised to lowercase)
 * @param lang - Preferred language to resolve the article in
 *
 * @returns The matching `InsightItem` (with full `content`), or `null` if not found
 */
export async function getArticleBySlug(slug: string, lang: 'en' | 'ar'): Promise<InsightItem | null> {
  const normalized = slug.toLowerCase();

  // Stage 1: Direct hit on the article-specific Redis key
  try {
    const article = await getWithCompression<InsightItem>(`insights:article:${normalized}`);
    if (article) return article;
  } catch (e) {
    // Swallowed intentionally — fall through to next stage
  }

  // Stage 2: Fuzzy match against the metadata list
  // Handles slugs that were stored with a hash suffix (e.g. "uae-economy-a1b2c3")
  // where the incoming slug may be the unhashed base ("uae-economy")
  const list = await getUnifiedInsights({ lang, limit: 1000 });
  const fuzzyMatch = list.find(p => {
    const pSlug = p.slug.toLowerCase();
    if (pSlug === normalized) return true;
    const basePart = normalized.includes('-') ? normalized.split('-').slice(0, -1).join('-') : normalized;
    return pSlug.startsWith(basePart + '-');
  });

  if (fuzzyMatch) {
    // Attempt to fetch the full content key using the list's canonical slug
    try {
      const fullArticle = await getWithCompression<InsightItem>(`insights:article:${fuzzyMatch.slug}`);
      if (fullArticle) return fullArticle;
    } catch (e) {
      // Swallowed intentionally — fall through to content check
    }
    // If the list item already carries content (legacy archive format), return it directly
    if (fuzzyMatch.content) return fuzzyMatch;
  }

  // Stage 3: Cross-language fallback — try the same slug in the other language
  try {
    const otherArticle = await getWithCompression<InsightItem>(`insights:article:${normalized}`);
    if (otherArticle) return otherArticle;
  } catch (e) {
    // Swallowed intentionally
  }

  return null;
}

/**
 * Returns all known article slugs for both languages, used by the sitemap generator.
 *
 * Fetches the full metadata list for English and Arabic, then combines and labels them.
 * The sitemap generator is responsible for deduplication and capping at 2000 entries.
 *
 * @returns Array of `{ slug, lang, pubDate }` objects for all indexed articles
 */
export async function getAllInsightSlugs(): Promise<{ slug: string; lang: 'en' | 'ar'; pubDate: string }[]> {
  const enItems = await getUnifiedInsights({ lang: 'en', limit: 1000 });
  const arItems = await getUnifiedInsights({ lang: 'ar', limit: 1000 });

  const enSlugs = enItems.map(n => ({ slug: n.slug, lang: 'en' as const, pubDate: n.pubDate }));
  const arSlugs = arItems.map(n => ({ slug: n.slug, lang: 'ar' as const, pubDate: n.pubDate }));

  return [...enSlugs, ...arSlugs];
}
