name            = "arabiakhaleej-contact"
main            = "worker.js"
compatibility_date = "2024-09-23"

[[routes]]
pattern = "arabiakhaleej.com/api/invite"
zone_name = "arabiakhaleej.com"

[[send_email]]
name                = "SEND_EMAIL"
destination_address = "asishchilakapati@gmail.com"
